add a new parameter @source_as_temp_table to improve merge script performance
dnlnln/generate-sql-merge pull request #16
Opened 2016-01-14 01:11 UTC by simonwangu

we have a table with about 5k records need to generate a merge script,
while I choose to not delete when not matched SQL Server would complaint
that 'query processor ran out of internal resources'.

I suppose as the merge source is all in memory and causing the trouble,
I moved all source into a temporary table and then use that as the
source for the merge and the script ran successful without any problem.

This doesn't mean it will run faster, in fact it might even slow it down
on limited disk resource servers, but at least it would run as SQL
Server won't consume too much memory to form the source table which
might causing the error.

ACTUAL ERROR is:

Msg 8623, Level 16, State 1, Line 8
The query processor ran out of internal resources and could not produce
a query plan. This is a rare event and only expected for extremely
complex queries or queries that reference a very large number of tables
or partitions. Please simplify the query. If you believe you have
received this message in error, contact Customer Support Services for
more information.

2018-02-05 08:04 UTC, readyroll commented
Thank you for your contribution and sorry that it's taken over 2 years to review this in detail!

Per your notes, this PR contains the following changes (paraphrased slightly by me, in order to ensure that I've understood them correctly):

1. When installing the utility, it is now installed into the current db context, rather than in `master`
2. Previously, the query would be really slow when the table defined in `@table_name` contained a very large amount of data, and SQL Server would not even able to complete the MERGE query (I presume?) due to the need to form all of the data into a memory table. Therefore a new parameter has been introduced `@source_as_temp_table` which will put the raw data into a temporary table first and then use that as a source to improve performance
3. Along with @source_as_temp_table, @output_identity_into_temp will use OUTPUT keyword to write all matching identity pk back into the temporary table with extra '_Source' appended to the identity column name as a new column, so that when exporting linked record between table when identity insert is not an option
4. In order to make #3 mapping actually work @script_before_merge @script_after_merge was introduced to inject SQL code for mapping, which necessitated the addition of another parameter, @drop_temp_table
5. Added @ignore_duplicates_for_update so that when source data for no reason has duplicates except identity, re-running the script won't cause trouble with rownumber
6. Added @different_join_columns so that the match can be used on different columns
7. @different_join_nullable_columns is a subset of @different_join_columns to tell those columns might be nullable so that we match them with both null check on source and target

As this is quite a large submission, I'll respond to each point individually.

I can see the merits of (1), although I'd have a slight concern about the impact to those who are used to the proc installing into `master` as a system object. To offset this risk, it may be an idea to include some pre-deployment validation: if the current context is not `master`, the proc creation should not go ahead unless the `$(install_into_userdb)=1` SQLCMD variable is set, for example.

(2) looks good, although given that this adds a fairly large new codepath to the utility, I'm wondering if it would only be wise to add such complexity to the tool until some automated tests are put in place.

(3) not sure I fully understand the use case for the `@output_identity_into_temp`. Could you elaborate on the scenario you had in mind where identity insert isn't an option? (e.g. does it have something to do with runtime permissions when executing the `MERGE`?). Also would you be able to provide a bit more context to the params introduced in (4)?

(6) and (7) look good

Again this is quite a big submission but I can see that there is potentially a lot of value to be gained by the changes. I may be inclined to split off 1 and 6-7 into their own PRs to allow these to be merged in if you think that would work? 

Items 2-5 seem to be closely linked, and are a fair bit more complex than the other changes, so may be worth treating separately. Thoughts?

2018-02-05 08:05 UTC, dnlnln requested changes
Please see above comments

2018-02-07 20:36 UTC, simonwangu commented
Sorry I didn't meant to make one single pull request to be so big, but I just needed it to be all there to fulfill my need in a short period. I will spend some time to do some cherry picking to see if I can separate those changes into smaller branches and then create separate pull request.

2018-02-07 20:36 UTC, closed without merging

2018-02-08 04:37 UTC, readyroll commented
No worries at all, look forward to having a look at your contributions when you have a chance to submit them.