Added N to strings output for unicode handling on some collations
dnlnln/generate-sql-merge pull request #20
Opened 2017-03-21 15:55 UTC by nathfy

Hi, this sproc has been really useful for us in building seeddata for our tests. One thing I needed todo to get it working for us was to add `N` infront of the strings to fix the unicode inserts of text to NVARCHAR cols. This PR adds that in to the sproc.

Thanks for sharing it on github.

2017-03-27 00:40 UTC, dnlnln requested changes
Thanks for your contribution, I'm glad to hear you're getting good use out of it

Just left one comment for you, otherwise it looks good :)

2017-03-27 00:40 UTC, readyroll commented on master.dbo.sp_generate_merge.sql
> +END
This is causing an error when trying to deploy the proc:
```
Msg 102, Level 15, State 1, Line 668
Incorrect syntax near 'END'.
```

2017-05-01 21:17 UTC, Dezleung commented
for both binary and varbinary, it should use CONVERT(varchar(max), @column_name, 1) to generate HEX string as Source Value.

2017-05-02 09:03 UTC, nathfy commented
Hi there @readyroll changes made, and @Dezleung I've updated the binary and varbinary conversions as you suggested. Take a look if you have time

Thanks

2017-05-03 08:28 UTC, dnlnln approved these changes

2017-05-03 08:28 UTC, merged